### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by ElStabilini** [ElStabilini/optimization#28]
### ML optimization (DRAG, amplitude & frequency)
- [ ] extend optuna to more than 500 epochs
- [ ] test other qubits and save results

### Qibocal contributions
- [ ] RX($\pi/2$) calibration
- [ ] Cryoscope
