### ISSUE TITLE
TO DO 

### ISSUE THREAD

**Issue by ElStabilini** [ElStabilini/optimization#29]
##To-do list for implementation and testing of rabi for RX($\pi/2$):

- [x] RX($\pi/2$) Rabi amplitude (modify, baseline, test)
- [x] RX($\pi/2$) Rabi length (modify, baseline, test)
- [x] RX($\pi/2$) Rabi amplitude frequency (modify, baseline, test) 
- [x] add a flag for switching from RX($\pi/2$) to RX($\pi$)
- [ ] Evaluate impact on calibration precision

## Sub-list for  adding flag
- [x] insert flag in function 
- [x] Modify input parameters in each Rabi routine
- [x] Modify _update method in all routine (we update only if we calibrate RX($\pi/2$)
- [x] modify qibolab native
